version: '3'
services:
  blockchain-api:
    container_name: blockchain-api
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    healthcheck:
      test: curl --fail -s http://danilojakob.ch:10000/api/get_chain || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
